<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'e2a538285cf59c83c7c8cbd273e0fcf6' => $baseDir . '/app/Helpers/CustomHelper.php',
);
