<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit54152a64f17649744df4da7ddb06b47a
{
    public static $files = array (
        'e2a538285cf59c83c7c8cbd273e0fcf6' => __DIR__ . '/../..' . '/app/Helpers/CustomHelper.php',
    );

    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Database\\Seeders\\' => 17,
            'Database\\Factories\\' => 19,
        ),
        'A' => 
        array (
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Database\\Seeders\\' => 
        array (
            0 => __DIR__ . '/../..' . '/database/seeders',
        ),
        'Database\\Factories\\' => 
        array (
            0 => __DIR__ . '/../..' . '/database/factories',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/app',
        ),
    );

    public static $classMap = array (
        'App\\CommonFunctions' => __DIR__ . '/../..' . '/app/CommonFunctions.php',
        'App\\Http\\Controllers\\ActivityLogController' => __DIR__ . '/../..' . '/app/Http/Controllers/ActivityLogController.php',
        'App\\Http\\Controllers\\ApplicantController' => __DIR__ . '/../..' . '/app/Http/Controllers/ApplicantController.php',
        'App\\Http\\Controllers\\ApplicationController' => __DIR__ . '/../..' . '/app/Http/Controllers/ApplicationController.php',
        'App\\Http\\Controllers\\ApplicationDetailController' => __DIR__ . '/../..' . '/app/Http/Controllers/ApplicationDetailController.php',
        'App\\Http\\Controllers\\AuthController' => __DIR__ . '/../..' . '/app/Http/Controllers/AuthController.php',
        'App\\Http\\Controllers\\Auth\\LoginController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/LoginController.php',
        'App\\Http\\Controllers\\Auth\\ResetPasswordController' => __DIR__ . '/../..' . '/app/Http/Controllers/Auth/ResetPasswordController.php',
        'App\\Http\\Controllers\\Controller' => __DIR__ . '/../..' . '/app/Http/Controllers/Controller.php',
        'App\\Http\\Controllers\\DistrictController' => __DIR__ . '/../..' . '/app/Http/Controllers/DistrictController.php',
        'App\\Http\\Controllers\\DivisionController' => __DIR__ . '/../..' . '/app/Http/Controllers/DivisionController.php',
        'App\\Http\\Controllers\\DocUploadController' => __DIR__ . '/../..' . '/app/Http/Controllers/DocUploadController.php',
        'App\\Http\\Controllers\\ILRController' => __DIR__ . '/../..' . '/app/Http/Controllers/ILRController.php',
        'App\\Http\\Controllers\\LandAllocationTempController' => __DIR__ . '/../..' . '/app/Http/Controllers/LandAllocationTempController.php',
        'App\\Http\\Controllers\\MasterAttachmentController' => __DIR__ . '/../..' . '/app/Http/Controllers/MasterAttachmentController.php',
        'App\\Http\\Controllers\\MasterRoleController' => __DIR__ . '/../..' . '/app/Http/Controllers/MasterRoleController.php',
        'App\\Http\\Controllers\\RegisterController' => __DIR__ . '/../..' . '/app/Http/Controllers/RegisterController.php',
        'App\\Http\\Controllers\\SSOUserController' => __DIR__ . '/../..' . '/app/Http/Controllers/SSOUserController.php',
        'App\\Http\\Controllers\\TehsilController' => __DIR__ . '/../..' . '/app/Http/Controllers/TehsilController.php',
        'App\\Http\\Controllers\\TemporaryLandAllocationController' => __DIR__ . '/../..' . '/app/Http/Controllers/TemporaryLandAllocationController.php',
        'App\\Http\\Controllers\\UserController' => __DIR__ . '/../..' . '/app/Http/Controllers/UserController.php',
        'App\\Http\\Controllers\\UserLogController' => __DIR__ . '/../..' . '/app/Http/Controllers/UserLogController.php',
        'App\\Http\\Controllers\\VillageController' => __DIR__ . '/../..' . '/app/Http/Controllers/VillageController.php',
        'App\\Http\\Middleware\\SetLocale' => __DIR__ . '/../..' . '/app/Http/Middleware/SetLocale.php',
        'App\\Http\\Requests\\ActivityLogRequest' => __DIR__ . '/../..' . '/app/Http/Requests/ActivityLogRequest.php',
        'App\\Http\\Requests\\ApplicantRequest' => __DIR__ . '/../..' . '/app/Http/Requests/ApplicantRequest.php',
        'App\\Http\\Requests\\DistrictRequest' => __DIR__ . '/../..' . '/app/Http/Requests/DistrictRequest.php',
        'App\\Http\\Requests\\DivisionRequest' => __DIR__ . '/../..' . '/app/Http/Requests/DivisionRequest.php',
        'App\\Http\\Requests\\DocUploadRequest' => __DIR__ . '/../..' . '/app/Http/Requests/DocUploadRequest.php',
        'App\\Http\\Requests\\ILRRequest' => __DIR__ . '/../..' . '/app/Http/Requests/ILRRequest.php',
        'App\\Http\\Requests\\MasterAttachmentRequest' => __DIR__ . '/../..' . '/app/Http/Requests/MasterAttachmentRequest.php',
        'App\\Http\\Requests\\MasterRoleRequest' => __DIR__ . '/../..' . '/app/Http/Requests/MasterRoleRequest.php',
        'App\\Http\\Requests\\SSOUserRequest' => __DIR__ . '/../..' . '/app/Http/Requests/SSOUserRequest.php',
        'App\\Http\\Requests\\TehsilRequest' => __DIR__ . '/../..' . '/app/Http/Requests/TehsilRequest.php',
        'App\\Http\\Requests\\TemporaryLandAllotmentRequest' => __DIR__ . '/../..' . '/app/Http/Requests/TemporaryLandAllotmentRequest.php',
        'App\\Http\\Requests\\UserLogRequest' => __DIR__ . '/../..' . '/app/Http/Requests/UserLogRequest.php',
        'App\\Http\\Requests\\UserRequest' => __DIR__ . '/../..' . '/app/Http/Requests/UserRequest.php',
        'App\\Http\\Requests\\VillageRequest' => __DIR__ . '/../..' . '/app/Http/Requests/VillageRequest.php',
        'App\\Models\\ActivityLog' => __DIR__ . '/../..' . '/app/Models/ActivityLog.php',
        'App\\Models\\Application' => __DIR__ . '/../..' . '/app/Models/Application.php',
        'App\\Models\\ApplicationDetail' => __DIR__ . '/../..' . '/app/Models/ApplicationDetail.php',
        'App\\Models\\ApplicationRule' => __DIR__ . '/../..' . '/app/Models/ApplicationRule.php',
        'App\\Models\\ApplicationTransaction' => __DIR__ . '/../..' . '/app/Models/ApplicationTransaction.php',
        'App\\Models\\District' => __DIR__ . '/../..' . '/app/Models/District.php',
        'App\\Models\\Division' => __DIR__ . '/../..' . '/app/Models/Division.php',
        'App\\Models\\DocUpload' => __DIR__ . '/../..' . '/app/Models/DocUpload.php',
        'App\\Models\\ForwardToRoles' => __DIR__ . '/../..' . '/app/Models/ForwardToRoles.php',
        'App\\Models\\LandAllocationTemp' => __DIR__ . '/../..' . '/app/Models/LandAllocationTemp.php',
        'App\\Models\\LandDetail' => __DIR__ . '/../..' . '/app/Models/LandDetail.php',
        'App\\Models\\LandOwnerDetail' => __DIR__ . '/../..' . '/app/Models/LandOwnerDetail.php',
        'App\\Models\\MasterAttachment' => __DIR__ . '/../..' . '/app/Models/MasterAttachment.php',
        'App\\Models\\MasterRole' => __DIR__ . '/../..' . '/app/Models/MasterRole.php',
        'App\\Models\\Organization' => __DIR__ . '/../..' . '/app/Models/Organization.php',
        'App\\Models\\Purpose' => __DIR__ . '/../..' . '/app/Models/Purpose.php',
        'App\\Models\\SSOUser' => __DIR__ . '/../..' . '/app/Models/SSOUser.php',
        'App\\Models\\Sanstha' => __DIR__ . '/../..' . '/app/Models/Sanstha.php',
        'App\\Models\\TblUser' => __DIR__ . '/../..' . '/app/Models/TblUser.php',
        'App\\Models\\Tehsil' => __DIR__ . '/../..' . '/app/Models/Tehsil.php',
        'App\\Models\\TemporaryLandAllocation' => __DIR__ . '/../..' . '/app/Models/TemporaryLandAllocation.php',
        'App\\Models\\User' => __DIR__ . '/../..' . '/app/Models/User.php',
        'App\\Models\\UserLog' => __DIR__ . '/../..' . '/app/Models/UserLog.php',
        'App\\Models\\Village' => __DIR__ . '/../..' . '/app/Models/Village.php',
        'App\\Providers\\AppServiceProvider' => __DIR__ . '/../..' . '/app/Providers/AppServiceProvider.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'Database\\Factories\\UserFactory' => __DIR__ . '/../..' . '/database/factories/UserFactory.php',
        'Database\\Seeders\\DatabaseSeeder' => __DIR__ . '/../..' . '/database/seeders/DatabaseSeeder.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit54152a64f17649744df4da7ddb06b47a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit54152a64f17649744df4da7ddb06b47a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit54152a64f17649744df4da7ddb06b47a::$classMap;

        }, null, ClassLoader::class);
    }
}
